name: Compile HTML

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build HTML
        run: |
          make docker && \
          make html && \
          # `index.html` for GitHub Pages
          cp build/html/resume.html build/html/index.html
      - name: Upload HTML as artifact
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html/
          publish_branch: gh-pages
          force_orphan: true
