# Based on "Github Action for LaTeX"
#  ==> https://github.com/marketplace/actions/github-action-for-latex

name: Compile LaTeX PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize repo
        uses: actions/checkout@v2
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume/main.tex


